/**
 * Las sinopsis del catálogo real, tal como las publica la ficha de cada serie
 * en idilio.tv. Son el texto que la app nativa muestra bajo «Resumen».
 *
 * GENERADO por scripts/sinopsis.mjs desde docs/00-dogfooding/catalogo.json.
 * No editar a mano: el catálogo es del producto, no del prototipo.
 *
 * 2 de las 41 series con muro no tienen sinopsis cargada —Mi Esposo es la Muerte, Somos Cuatro—
 * y no aparecen acá. En esas, el sitio real repite el título en el lugar del
 * resumen, y la ficha del POC hace lo mismo.
 */
export const SINOPSIS: Record<string, string> = {
  'sangre-enemiga':
    "Isabella Botero, hija del cazador de vampiros más temido, es secuestrada por Magnus, el despiadado líder del clan Valmont, para obligar a su padre a traicionar a los humanos. Prisionera en el castillo enemigo, conoce a Lorenzo, el heredero del clan: un vampiro que nunca eligió su destino y empieza a desafiar a Magnus para protegerla. Mientras el odio se vuelve un amor imposible, Isabella descubre que la guerra esconde siglos de dolor… y que su libertad tendrá un precio devastador.",
  'mi-mejor-pasajera':
    "Jimena, una asistente de aeropuerto que sueña con ser piloto sin haber volado jamás, encuentra el amor en un piloto que convierte su rutina en una aventura. Pero un diagnóstico terminal le da solo tres meses de vida y sepulta su sueño. Entonces él decide regalarle el mundo sin despegar del suelo, recreando destinos inolvidables para que viva los viajes que nunca hará. Entre despedidas, ilusiones y un amor que desafía al tiempo, descubrirán que no hace falta volar para llegar al corazón amado.",
  'apasionada-por-el-padre-de-mi-hijo-que':
    "Mariana Arango, heredera de un imperio, vive atrapada junto a Felipe, un hombre que solo la ama por su fortuna. Durante unas vacaciones en la casa de campo familiar, conoce a Sebastián, un misterioso jardinero que despierta en ella una pasión imposible de ocultar. Años después, casada e infeliz, un secreto amenaza con derrumbarlo todo: quizás el padre de su hijo no es su esposo. Entre engaños, celos y peligro, Mariana deberá elegir entre la vida que le impusieron y el amor que la libera.",
  'simona-la-libertadora-enamorada':
    "En plena campaña libertadora de 1819, Simona Amaya se enamora del legendario capitán Juan José Rondón y comprende que su lugar no está esperando en casa, sino luchando por la libertad. Disfrazada de hombre, se une al ejército patriota en un viaje donde el amor florece más allá de las apariencias y de los cuerpos. Junto a Rondón sella una promesa capaz de desafiar a la muerte… y convertirla en una de las leyendas más extraordinarias de la independencia.",
  'la-mas-hermosa-y-el-espejo':
    "Ana, de 18 años, sueña con actuar, pero vive a la sombra de su madre: Isadora, una diva obsesionada con la fama, la juventud y el poder. Cuando madre e hija compiten por el mismo papel, la belleza y el talento de Ana despiertan en Isadora unos celos capaces de todo. Obligada a huir, Ana halla refugio entre un grupo de artistas marginados que le enseñan lo que es un verdadero hogar. Una reinvención oscura de un cuento clásico sobre la vanidad, el amor y el coraje de brillar con luz propia.",
  'la-venganza-de-una-esposa-despues-de-l':
    "Sofía, una brillante arquitecta y diseñadora, lo sacrificó todo por amor, solo para ser traicionada y asesinada por el hombre que más amaba. Ahora, tras recibir una inesperada segunda oportunidad para vivir, está decidida a reescribir su destino.",
  'aun-sigues-siendo-tu':
    "Isabel creía haber dejado atrás a Julián, pero su corazón no obedece. Atrapada entre un prometido cada vez más violento y el primer amor que la marcó, debe decidir a quién escuchar. Mientras tanto, un fantasma del pasado de Julián reaparece dispuesto a destruirlo todo y lo empuja a decisiones que podrían costarle su carrera, su libertad… y a ella. Entre chantajes, secretos y una red criminal que los acecha, el amor deberá sobrevivir a su prueba más peligrosa. ¿Sigues siendo tú después de todo?",
  'la-bandida-que-me-amo':
    "Valentina Morales, «La Peligrosa», lidera la temida pandilla Los Escorpiones… hasta que cae en manos de la policía. Tras las rejas la espera Vargas, un subteniente incorruptible que debería odiarla, pero no logra dejar de mirarla. Entre golpes, traiciones y una fuerza policial podrida por dentro, el deber y el deseo chocan sin tregua. Y mientras casi todos la quieren muerta, un viejo secreto sobre su origen amenaza con cambiarlo todo. ¿Puede nacer el amor entre una criminal y su carcelero?",
  'mi-final-feliz':
    "Daniela lucha por pagar la matrícula y sueña con escribir la historia de amor perfecta. Julián es la estrella que todos admiran… y que ella desprecia, hasta que un profesor los obliga a escribir juntos. Entre roces, una ex que no se rinde y un secreto que él guarda, dos mundos opuestos chocan en cada página. ¿Lograrán escribir su propio final feliz, o la vida les tiene preparado otro guion? Una comedia romántica sobre el amor, los sueños y las segundas oportunidades.",
  'aun-eres-tu':
    "Julián era el rey de la cancha del barrio e Isabel, la mujer que lo amaba. Una promesa, una despedida sin explicación y siete años de silencio. Hoy él es una estrella mundial y ella está a punto de casarse… cuando el destino vuelve a cruzar sus caminos. Entre miradas que aún arden, celos y secretos que nadie se atreve a nombrar, una sola pregunta lo enciende todo: ¿puede el primer amor sobrevivir al tiempo, a la fama y a todo lo que quedó sin decir?",
  'tres-meses-de-amor':
    "Natalia es una joven trabajadora de un parque acuático que se esfuerza para mantener a su abuela en México. Sus compañeras descubren que tiene una hermosa voz y la invitan a ser la vocalista de su banda musical.",
  'quiero-a-mi-ex-fuera-de-mi-vida':
    "Atrapada en una jaula dorada de traición, el mundo de Sophie se hace añicos cuando la aventura de su esposo Ben desemboca en un trágico aborto espontáneo. Bajo el gélido control de su suegra Olivia y las ponzoñosas intrigas de la amante Bella, Sophie lucha por recuperar su carrera médica con la ayuda del enigmático cirujano Alex. Pero, a medida que la obsesión de Ben se intensifica y los planes letales de Bella escalan, estalla un enfrentamiento incendiario.",
  'enamorandome-de-mi-guardian-prohibido':
    "Tras perder a sus padres en un accidente automovilístico, Leeann fue acogida por Dallas, un viejo amigo de la familia. Con los años, ella se enamoró de Dallas, pero él la rechazó para protegerla de la verdad: la muerte de sus padres podría estar relacionada con su familia, hasta que el desamor finalmente la obligó a marcharse.",
  'la-venganza-de-la-abogada':
    "Elly Spears, la invicta reina del derecho, construyó en secreto un imperio global, pero lo abandonó todo por amor. Tras casarse con George, se convirtió en ama de casa, solo para ser traicionada. Durante el mediático caso de asesinato de Louis, George se atribuye el mérito y empuja a Elly al límite. Humillada y con el corazón roto, pierde a su hijo y jura vengarse.\nCuando Elly regresa para reclamar su poder, se reencuentra con Will Carpio, un multimillonario oculto que siempre la ha amado. Junto",
  'abrazame-fuerte-senor-bombero':
    "Raymond Longwood puede ser un heroico bombero de día, pero bajo el uniforme se esconde un secreto: también es el único heredero del poderoso Grupo Longwood. Presionado por su abuelo para casarse, Raymond se niega a hacerlo hasta encontrar a la misteriosa chica que una vez le salvó la vida en medio de un incendio feroz.",
  'mi-amante-secreto':
    "Yo solo era una amante oculta. Mi mayor error fue enamorarme de un hombre de corazón frío. Luego descubrí que estaba embarazada. Pensé que, tal vez, ahora por fin vería mi corazón.\nPero para él, yo no era más que una espía, enviada para vigilar cada uno de sus movimientos. Cuando perdí al bebé, decidí irme. Pero justo cuando estaba a punto de marcharme, ese hombre frío… ¿apareció suplicando mi perdón? No estoy segura de querer volver.",
  'esposo-fugitivo-amame-otra-vez':
    "Tras decidir divorciarse del magnate empresarial Alexis, incapaz de seguir tolerando su matrimonio por contrato, la acaudalada heredera Vylina cayó en el punto más bajo de su vida. Sin embargo, después de soportar los duros golpes de los momentos más oscuros, finalmente alcanzó un éxito abundante tanto en su carrera como en su vida amorosa.",
  'esposa-del-playboy-billonario':
    "Bajo la presión de su madrastra, Alicia sustituye a su hermana para casarse con un desconocido. Descorazonada, encuentra consuelo por una noche en la compañía de Lucius. Más tarde, durante la boda, descubre que Lucius es el novio, dando inicio a una inesperada historia de amor.",
  'pasion-frente-a-los-colmillos-del-cond':
    "En Transilvania de 1795, el oscuro Conde Konrad contrata a la humilde Elisa para fingir un matrimonio. Lo que inicia como un trato frío pronto desata una pasión irresistible que despierta la humanidad del noble. Pero cuando su exesposa inmortal regresa y un pueblo enfurecido cerca el palacio, la tragedia los acecha. ¿Podrá su amor sobrevivir a la oscuridad o serán consumidos por el odio?",
  'la-venganza-de-la-hija-del-esmeraldero':
    "Cielo, la exitosa dueña de un imperio joyero, ve su vida perfecta destruida cuando un asalto amañado revela la peor de las traiciones: su prometido y su mejor amiga son amantes y buscan destruirla. Injustamente acusada, su única esperanza es Rosa, la brillante y solitaria detective a cargo del caso. Mientras unen fuerzas para destapar la oscura verdad, su alianza despierta una atracción prohibida e innegable. Cruzando límites éticos y personales, su lucha por la justicia se transforma en una apa",
  'rico-padre-pobre-madre':
    "La heredera Laila es expulsada de su casa tras un embarazo inesperado. Años después, el padre de su hijo, Roman, aparece, revelando que es el hombre más rico del mundo. Para conseguir tratamiento médico para su hijo, Laila acepta un matrimonio por contrato con Roman. Sin embargo, a medida que se conocen, poco a poco rompen el contrato y se enamoran.",
  'la-mesera-millonaria':
    "Para salvar su imperio gastronómico de la ruina, una brillante ejecutiva se infiltra en su propio restaurante disfrazada de mesera. Entre sartenes y traiciones, descubrirá un oscuro complot y a un humilde compañero con un talento excepcional que pondrá su corazón en jaque. En una cocina donde nadie es quien dice ser, ¿qué pesará más: el amor o la ambición?",
  'enamorada-de-la-voz-del-lobo':
    "Para atrapar a un asesino brillante y despiadado, la intachable inspectora Lucía Andrade debe hacer un pacto impensable: pedirle ayuda a Gabriel \"El Lobo\", el letal criminal que ella misma encarceló. Obligada a confiar en un hombre que conoce la oscuridad mejor que nadie, Lucía se adentrará en un peligroso juego psicológico de manipulación y deseo prohibido. Cuando cazas de la mano de un monstruo, la línea entre la justicia y el pecado desaparece... ¿Quién terminará cazando a quién?",
  'habia-una-vez-un-divorcio-la-doble-vid':
    "Tras ser traicionada, la hija secreta de un multimillonario entra inesperadamente en un matrimonio por contrato con un acaudalado magnate. Juntos, derriban al ex engañoso y enfrentan intensas rivalidades familiares, hasta que finalmente encuentran su propio camino hacia la felicidad.",
  'el-pecado-de-nuestro-amor':
    "Pablo, un joven millonario, decide casarse con Diana, la hija de la sirvienta, desatando la furia de su madre Sara. El amor se convierte en pesadilla cuando descubren que podrían ser hermanos debido a un oscuro secreto. Entre engaños, asesinatos y ambición desmedida, deberán enfrentar a villanos despiadados para descubrir su verdadero origen. Al final, la verdad sale a la luz: no comparten sangre y su amor triunfa sobre la tragedia, heredando un futuro juntos.",
  'creo-que-mi-esposa-quiere-matarme':
    "La vida de Emily cambia cuando su jefe, Dominic, le pide espiar a su esposa Vivian, alegando que intentó matarlo. Infiltrada, Emily descubre que Dominic se hirió a sí mismo para incriminar a Vivian y quedarse con la fortuna. Atrapada en una guerra de manipuladores, debe decidir su lealtad. La situación se vuelve mortal cuando hallan el cuerpo de Lady Martha y Emily es incriminada injustamente por el asesinato, obligándola a enfrentar a un detective mientras lucha por la verdad.",
  'la-herencia-del-patriarca-enamorado':
    "El magnate Germán Kopel reúne a su ambiciosa familia para celebrar sus 75 años, ocultando un cáncer terminal. Su anuncio de boda con la joven Lorena desata una guerra por la sucesión de la Corporación. Entre intrigas, se revela un secreto devastador: Lorena y Santiago, el hijo menor, tuvieron un romance en el pasado. Tras la muerte del patriarca, una votación empatada deja el destino del imperio en manos del instinto de un perro, coronando a la persona menos esperada",
  'las-flores-del-amor':
    "Para heredar el imperio floral de su abuela, Dennis debe casarse antes de San Valentín. Desesperada, contrata a \"Felipe\" como prometido falso, ignorando que en realidad es Juan José, heredero de su mayor rival comercial. Entre conspiraciones familiares e identidades ocultas, el acuerdo se transforma en amor verdadero. ¿Podrá su relación sobrevivir a la verdad cuando su tío intente vender el legado y destruir la boda? Una historia donde el amor florece entre espinas.",
  'enamoradas-del-motociclista-mafioso':
    "Traicionada por su esposo y su hermana, Natalia lo pierde todo hasta que Joaquín, un misterioso motociclista y heredero oculto del Cartel King, la rescata. En una guerra donde el poder del cartel depende de engendrar al primer nieto, ambos enfrentan una red de tráfico infantil, mentiras y pruebas de ADN falsificadas. ¿Podrá el amor verdadero vencer la ambición y limpiar el legado de sangre en Bahía Magdalena?",
  'mi-apuesto-guardaespaldas':
    "N/A",
  'intenciones-ocultas':
    "David y Mia están locamente enamorados y han decidido casarse. Se mudan juntos y su amor se fortalece cada día más. Mia hace algunos cambios en la casa y contrata a Sara, una mujer mayor, como empleada doméstica.\nPronto comienzan a suceder cosas extrañas en la casa. David enferma y decide contratar a una enfermera, Amy, para que lo cuide. David se acostumbra a sus atenciones, lo que podría afectar su amor por Mia.\nMuy pronto, Amy descubre la causa de la enfermedad de David.",
  'la-enfermera-infiltrada':
    "La Enfermera Infiltrada cuenta la historia de Valeria, una mujer que se infiltra como enfermera en la casa de una familia poderosa para descubrir la verdad sobre Daniela, una joven cuya muerte nunca fue aclarada. Mientras aparenta cumplir su trabajo, Valeria se enfrenta a mentiras, manipulaciones y secretos que la arrastran a un juego peligroso. Cada capítulo revela nuevas verdades y demuestra que, cuando el poder lo controla todo, decir la verdad puede costarlo todo.",
  'el-juego-de-la-herencia':
    "Emma Lawson, una trabajadora social, hereda inesperadamente la fortuna de Jonathan Kingsley con una sola condición: vivir un año en Kingsley Manor junto a su ambiciosa familia, excluida del testamento. Rodeada de envidia, engaños y juegos de poder, Emma encuentra apoyo en Alexander, el hijo menor, con quien surge un romance que amenaza los planes familiares. Mientras los secretos de la mansión salen a la luz, Emma descubre que el verdadero reto no es heredar la fortuna, sino sobrevivir a ella.",
  'el-hermanastro-enamorado':
    "Cuando Carmen y Hugo se casan, sus hijos adolescentes, Gabriel y Victoria, se ven obligados a vivir juntos. Lo que inicia como rivalidad se transforma en una atracción prohibida que desata rumores, un video viral y un escándalo escolar. Daniela, obsesionada con Gabriel, manipula pruebas y redes para destruir a Victoria, mientras un profesor corrupto aprovecha la situación para acosarla. Entre mentiras, traiciones y exposición pública, Gabriel y Victoria deberán luchar por su amor antes de que el",
  'la-magica-navidad-del-amargado-millona':
    "La mágica Navidad del Amargado Millonario cuenta la historia de José Soto, un millonario frío y despiadado que odia la Navidad y dirige su empresa sin corazón. Su vida da un giro inesperado cuando Silvia, una empleada madre soltera que lucha por salvar la vida de su hija, lo enfrenta y termina secuestrada junto a él.\nObligados a sobrevivir en cautiverio, José y Silvia descubren verdades profundas, heridas del pasado y un lazo que jamás imaginaron.\nEntre disparos, milagros y una Nochebuena que lo cambia todo, José renace convertido en Pepe, el hombre capaz de amar, de dar… y de transformar la Navidad de todos a su alrededor.",
  'milagro-de-amor-en-nochebuena':
    "En Nochebuena, una tormenta reúne en la casa de Matilde a Rosa, su antiguo amor Miguel y Julián, un obrero marcado por la injusticia. Entre rezos y buñuelos, salen a la luz una paternidad oculta, un despido injusto y un plan de venganza. A medianoche, deberán elegir entre el rencor o el perdón para proteger a los mellizos.",
  'buscando-a-mi-padre-me-enamore-de-mi-h':
    "Margarita, una humilde y rebelde vendedora de flores, emprende la búsqueda de su padre sin imaginar que el destino la llevará a las puertas del lujoso imperio Rosalinda. Allí, tras un accidente, es acogida por Camilo, un joven heredero comprometido con otra mujer. Entre secretos, mentiras y una pasión prohibida, ambos se enamoran sin saber que la sangre podría unirlos más de lo permitido. Amor, traición y venganza se entrelazan en una historia donde cada beso puede ser un pecado... y cada verdad, una sentencia.",
  'la-ninera-poderosa':
    "Alejandro, un exitoso ejecutivo y padre viudo, cree haber encontrado paz al contratar a Camila, una joven niñera que devuelve la risa a su hija Daniela. Lo que parece un nuevo comienzo se convierte en una historia de pasión prohibida, secretos familiares y peligros ocultos, donde nada es lo que parece. Entre la ternura y la traición, Camila deberá demostrar que no es solo una niñera, sino la única capaz de salvar a la familia de un destino mortal.",
  'pasion-a-domicilio':
    "Ximena, una repartidora trabajadora que lucha por salvar a su madre enferma, nunca imaginó que un simple domicilio la llevaría a cruzar la puerta de la lujosa Mansión Silva… y directo a un torbellino de pasiones, secretos y peligros. Entre el magnético Federico Silva, heredero problemático, y un entorno de poder, engaños y traiciones, Ximena descubrirá que el amor puede ser tan intenso como arriesgado, y que cada decisión puede costarle su libertad… o su vida.",
}
